### ISSUE TITLE
Some small problems

### ISSUE THREAD

**Issue by luizzeroxis** [dimdenGD/YeahTwitter#1]
1. Can you make it so doesn't almost automatically follow you lol (don't make the big button just do that)
2. Can you make it so when you yeah it doesn't automatically like it
3. Can you make it so not only you are replacing likes, but actually entire posts that go into a separate website so you can post on both at the same time then add in all the features so it actually takes over Twitter and no one needs to post there anymore

**Comment by dimdenGD** [comment]
1. it asks u if u want to follow
2. maybe will be option in future
3. whispy.org

**Comment by luizzeroxis** [comment]
1. Yeah, it asks but it's kind of a dark pattern!
2. Cool
3. Wow didn't know this was a thing, or I guess will be a thing, thanks for sharing it!!
