### ISSUE TITLE
YeahTwitter + OldTwitter incompatibility

### ISSUE THREAD

**Issue by epfly6** [dimdenGD/YeahTwitter#10]
Avatars are mostly displayed round when this option is turned off in the settings of the latter plugin
Browser: Firefox Developer Edition, all plugins are updated to the latest version
![image](https://github.com/dimdenGD/YeahTwitter/assets/36567300/f64c8ebc-9a08-469b-9dfb-2958bf9a3f64)

**Comment by dimdenGD** [comment]
Fixed
