### ISSUE TITLE
Quotes break the count

### ISSUE THREAD

**Issue by IPTVmanreal** [dimdenGD/YeahTwitter#17]
Opening a Quote Retweet while using the extension causes the "Yeah!" counter to use the values from the quoted Tweet

![image](https://github.com/dimdenGD/YeahTwitter/assets/99894372/5974cc07-fad8-4e06-872f-ee776a27ac10)

Example: [https://x.com/ShabblePony/status/1802711383420616945](https://twitter.com/ShabblePony/status/1802711383420616945)

**Comment by dimdenGD** [comment]
Update ur extension it was fixed
