### ISSUE TITLE
Quote Tweet Yeahs Aren't Listed

### ISSUE THREAD

**Issue by vampiricwulf** [dimdenGD/YeahTwitter#18]
When looking at the list of Yeah'd tweets on your profile, quote retweets are not listed.

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/YeahTwitter/assets/26517362/063c7f63-1596-493e-bbee-98b3a3885959)
works fine for me

**Comment by vampiricwulf** [comment]
Might be limited to ones containing only an image in the quote tweet, try: https://x.com/BloodyMoonia/status/1802760698570899608

**Comment by dimdenGD** [comment]
Thanks, should be fixed
