### ISSUE TITLE
not able to see who yeah'd a tweet

### ISSUE THREAD

**Issue by Benjamin2722** [dimdenGD/YeahTwitter#19]
using the latest firefox, can't do anything but left click and it just yeahs or unyeahs

**Comment by dimdenGD** [comment]
go to post engagements menu to see who yeahed tweet

**Comment by Benjamin2722** [comment]
thank you! could you put that in the description please :) if its already there I mustve missed it

**Comment by dimdenGD** [comment]
I mean its the same way as viewing who liked tweet... seems pretty intuitive to me...
