### ISSUE TITLE
Show users likes as well as yeahs

### ISSUE THREAD

**Issue by mariomadproductions** [dimdenGD/YeahTwitter#20]
Could you make it so you can see users likes as well as yeahs? Because otherwise you are missing likes from before this extension was installed, and from if people click the like button mistakenly instead of the yeah button.

**Comment by dimdenGD** [comment]
elon removed viewing likes, its not possible anymore

**Comment by mariomadproductions** [comment]
> elon removed viewing likes, its not possible anymore

Users can still view their own likes. That's all that'd be needed to send them to the extension's database, right?
