### ISSUE TITLE
Suggestion for shortkey

### ISSUE THREAD

**Issue by 2chanhaeng** [dimdenGD/YeahTwitter#28]
Add following codes after [this line](https://github.com/dimdenGD/YeahTwitter/blob/994172c843af3d9aa6b256d37111ea1113d7d121/scripts/content.js#L232).
```js
        button.closest("article").addEventListener("keydown", (e) => {
            if(e.key === "y") button.click();
        });
```
Then yeah with `y` key.

**Comment by dimdenGD** [comment]
you're free to create a pull request

**Comment by 2chanhaeng** [comment]
Thanks to accept my suggestion!
