### ISSUE TITLE
Suggestion: store each user's public likes on twitter itself

### ISSUE THREAD

**Issue by t4moxjc7** [dimdenGD/YeahTwitter#4]
e.g. via tweets in a thread (that people can mute if need be)

Advantages of this:
* data is stored within the profile's data itself on twitter - not reliant on a third party server
* non-extension users can see users' likes

**Comment by dimdenGD** [comment]
Def not, would limit it a lot and wouldnt allow viewing counters

**Comment by mariomadproductions** [comment]
I think it'd still be very useful as an additional option, as currently the reach of people's likes made using this extension, is limited to users of this extension.
