### ISSUE TITLE
YeahTwitter doesn't work with multiple accounts

### ISSUE THREAD

**Issue by minneyar** [dimdenGD/YeahTwitter#6]
If you're logged in with multiple accounts, YeahTwitter will only authenticate itself with the account that is currently active when it first loads.  The result is that when you switch to your secondary account and click the "Yeah" button, it is saved as a "Yeah" for your original account and not your second.

**Comment by dimdenGD** [comment]
Should support in 1.0.4 now! You'll need to press on "Clear account tokens" for it to start working properly
